image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-order.jar &

build_script:
  - sh: uname -a
  #- sh: sudo apt install -y chromium-browser
  - sh: sudo snap install chromium
  #- sh: ls /usr/bin
  - sh: ls -l /usr/bin/google-chrome
  - sh: ls -l /usr/bin/google-chrome-stable
  #- sh: sudo snap refresh chromium
  - sh: cd ./api-ci/rest	# переходим в директорию ./api-ci/rest
  - sh: echo "$PWD"
  - sh: chmod +x gradlew
  - sh: ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации
