image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - sh: cd ./api-ci/rest	# переходим в директорию ./api-ci/rest
  - sh: echo "$PWD"
  - sh: chmod +x gradlew
  - sh: ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации